---
# tasks file for database
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install required software
  apt:
    name:
      - mysql-server
      - python-mysqldb
    state: present
  become: yes

- name: Create mysql database
  mysql_db: name={{ swrve_mysql_db }} state=present
  no_log: true
  become: yes

- name: Create mysql user
  mysql_user:
    name={{ swrve_mysql_user }}
    password={{ swrve_mysql_password }}
    priv="{{ swrve_mysql_db }}.*:ALL"
    host=%
  no_log: true
  become: yes

- name: Allow remote hosts to connect
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    backrefs: yes
    regexp: '^bind-address'
    line: 'bind-address = {{ swrve_mysql_bind_address }}'
    state: present
  become: yes
  notify: restart mysql