---
# tasks file for cms
- name: Download WordPress
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
  become: yes

- name: Copy config to remote host
  template: src=wp-config.php.j2 dest=/var/www/wordpress/wp-config.php
  become: yes

- name: Update Apache DocumentRoot
  become: yes
  template: src=vhosts/default.conf.j2 dest=/etc/apache2/sites-available/{{ inventory_hostname }}.conf

- name: Update Apache SSL Config
  become: yes
  template: src=vhosts/default-ssl.conf.j2 dest=/etc/apache2/sites-available/{{ inventory_hostname }}-ssl.conf

- name: Enable Vhosts
  become: yes
  command: a2ensite {{ inventory_hostname }}.conf {{ inventory_hostname }}-ssl.conf
  notify:
    - restart apache

- name: Disable Directory Browsing
  template: src=htaccess.j2 dest=/var/www/wordpress/.htaccess
  become: yes